# Tested with GCC on GNU/Linux

CXX=c++
CXXFLAGS=-O3 -ffast-math -ansi ${EXTRA_FLAGS} 
LINK=c++ 
LIBS=-lm
OBJS=interpolator.o \
     interpolator/Base.o interpolator/Polynomial.o 

BINDIR=bin
EXE=${BINDIR}/interpolator

all: exe 

exe: ${EXE}

${EXE}: ${OBJS} ${BINDIR}
	${LINK} ${LIBS} -o ${EXE} ${OBJS}

.o: .h
	${CXX} -c -o $*.o $< 

${BINDIR}:
	mkdir -p ${BINDIR}

clean:
	rm -f *.o */*.o ${EXE}
	rmdir ${BINDIR} 2> /dev/null

